cc_library(
    name = "big_integer",
    srcs = ["big_integer.cc"],
    hdrs = ["big_integer.h"],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    copts = [],
    deps = [":big_integer"],
)